### PR TITLE
Issue 4: Adding issue templates

### LINKED ISSUE #4: Add Issues templates
Repository is missing issue templates like questions, bugs, etc.

### PR DESCRIPTION
**Pull request by rsk2**
Changes to resolve #4

### CODE REVIEW

**Comment by laysauchoa** [comment]
hi, thanks a lot, did you test if those are working? do you have some screenshots how they will look like?

**Comment by rsk2** [comment]
> hi, thanks a lot, did you test if those are working? do you have some screenshots how they will look like?

@laysauchoa  Yes they are working. Once this merged, when you try to create a new issue, following screen will be shown with 4 different issue types:

image


When you click on the issue type the screen for that particular type will be shown. Screen for bug:

image


Screen for documentation:

image


Screen for general feature request:

image


Screen for other:

image

**Comment by laysauchoa** [comment]
They look really good, thanks for contributing!

**Review by laysauchoa — APPROVED** [review]

**Comment by rsk2** [comment]
> They look really good, thanks for contributing!

Thanks!

**Pull request merged**
